DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS blog_tags;
DROP TABLE IF EXISTS blog_categories;
DROP TABLE IF EXISTS blog_likes;
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;